[pytest]
DJANGO_SETTINGS_MODULE = core.settings
pythonpath = backend
python_files = test_*.py *_test.py
addopts = -m "not integration" -p no:warnings
markers =
    integration: integration tests requiring external services
norecursedirs = scratch debug
