# Generated by Django 6.1 on 2026-08-11 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('description_text', models.TextField()),
                ('url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeJobMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ats_score', models.FloatField(blank=True, null=True)),
                ('missing_keywords', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_matches', to='job_matching.jobdescription')),
                ('resume_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_matches', to='resumes.resumeversion')),
            ],
        ),
        migrations.AddIndex(
            model_name='jobdescription',
            index=models.Index(fields=['owner'], name='job_matchin_owner_i_29825f_idx'),
        ),
        migrations.AddIndex(
            model_name='resumejobmatch',
            index=models.Index(fields=['resume_version'], name='job_matchin_resume__ca53ce_idx'),
        ),
        migrations.AddIndex(
            model_name='resumejobmatch',
            index=models.Index(fields=['job_description'], name='job_matchin_job_des_789fb3_idx'),
        ),
    ]
