# Generated by Django 6.1 on 2026-08-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_matching', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumejobmatch',
            old_name='missing_keywords',
            new_name='keyword_gaps',
        ),
        migrations.RemoveField(
            model_name='resumejobmatch',
            name='ats_score',
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='parsed_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='resumejobmatch',
            name='match_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumejobmatch',
            name='matched_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resumejobmatch',
            name='missing_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resumejobmatch',
            name='partial_matches',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resumejobmatch',
            name='recommendations',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
