# Generated by Django 6.1 on 2026-08-14 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_matching', '0002_rename_missing_keywords_resumejobmatch_keyword_gaps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumejobmatch',
            name='match_details',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
