# Generated by Django 6.1 on 2026-08-11 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(max_length=50)),
                ('raw_response', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='resumes.resumeversion')),
            ],
            options={
                'indexes': [models.Index(fields=['resume_version'], name='ai_aianalys_resume__aaf113_idx')],
            },
        ),
    ]
