# Generated by Django 6.1 on 2026-08-11 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumes', '0001_initial'),
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='generated_documents/')),
                ('format', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='resumes.resumeversion')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='templates.template')),
            ],
            options={
                'indexes': [models.Index(fields=['resume_version'], name='documents_g_resume__a5516e_idx')],
            },
        ),
    ]
