# Generated by Django 6.1 on 2026-08-11 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumesection',
            name='section_type',
            field=models.CharField(choices=[('personal', 'Personal Information'), ('experience', 'Experience'), ('education', 'Education'), ('skills', 'Skills'), ('projects', 'Projects'), ('summary', 'Summary'), ('certifications', 'Certifications'), ('awards', 'Awards'), ('languages', 'Languages'), ('volunteer', 'Volunteer Experience'), ('custom', 'Custom')], max_length=50),
        ),
    ]
