# Generated by Django 6.1 on 2026-08-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_alter_resumesection_section_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeversion',
            name='purpose',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
