# Generated by Django 6.1 on 2026-08-11 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumes', '0002_alter_resumesection_section_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATSAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.TextField(blank=True, null=True)),
                ('overall_score', models.IntegerField(default=0)),
                ('keyword_score', models.IntegerField(default=0)),
                ('skills_score', models.IntegerField(default=0)),
                ('experience_score', models.IntegerField(default=0)),
                ('formatting_score', models.IntegerField(default=0)),
                ('missing_keywords', models.JSONField(blank=True, default=list)),
                ('matched_keywords', models.JSONField(blank=True, default=list)),
                ('formatting_risks', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ats_results', to='resumes.resumeversion')),
            ],
        ),
    ]
